version: '3'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build:
      context: .
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./config/openvpn:/etc/openvpn
      - ./config/hosts:/etc/hosts
